### PR TITLE
Doing ReceiveContext unit testable

### PR DESCRIPTION
**Pull request by rogerex**
Hey, this will solve many issues of mock libraries to mock this method

### CODE REVIEW

**Comment by mayuanyang** [comment]
Hi @rogerex

Thanks for submitting the PR.

Your PR is actually a very good indicator that the original design was a bit tightly coupled, making it `virtual` will solve some mocking issues. HoweverI am thinking to push it one step further.

As `ReceiveContext` already implemented `IReceiveContext`, what do you think to let handlers take `IReceiveContext` as the dependency instead of `ReceiveContext`, this can solve the coupling issue as well as making it testable.

For handler, the codes might look like
`public async Task Handle(IReceiveContext<xxx> context, CancellationToken cancellationToken)`

And for `IReceiveContext`, it might look something like 
```
       TMessasge Message { get; }
       void RegisterService<T>(T service);
       bool TryGetService<T>(out T service);
       Dictionary<string, object> MetaData;
        Task PublishAsync(IEvent msg, CancellationToken cancellationToken = default(CancellationToken));
    }
```

Similar changes to `SendContext`.

Let me know what you think, and looking forward to hear from you soon

Regards
Eddy

**Comment by rogerex** [comment]
Yes, you are right, that is a better solution.

**Comment by mayuanyang** [comment]
Thanks rogerex, I will implement that.
In terms of timeframe, Do you urgently need the `virtual` PR to be merged? I can make it a DEV release to unblock you if required

**Comment by rogerex** [comment]
No, I do not, the task has a low priority, please let me know when the change is ready for nuget package.

**Comment by mayuanyang** [comment]
@rogerex I have implemented the changes and added some test codes here https://github.com/mayuanyang/Mediator.Net/blob/dev/src/Mediator.Net.Test/TestContext/TestUseCustomReceiveContext.cs
As this is a breaking changes, i have bumped up the major version of the nuget package to 3.0.0, it should be available once they are indexed

let me know what you think.
Regards
Eddy

**Comment by rogerex** [comment]
Sounds and looks good, we can decline this PR then

**Comment by mayuanyang** [comment]
Thanks for you feedback, let me know if i can help in anyway. 👍

**Pull request closed without merging**
